name: function_system
description: A function system for mmate
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # networking
  dio: ^5.7.0
  retrofit: ^4.4.1

  # json
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  # riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # file
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  image: ^4.5.2
  package_info_plus: ^8.2.1
  path: ^1.9.0

  # Native
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

  # interceptor
  zstandard_android: ^1.3.27
  zstandard_ios: ^1.3.27

  # storage
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.2
  realm: ^20.1.1

  # etc
  daum_postcode_search: ^0.0.3
  intl: ^0.20.2
  uuid: ^4.5.1

  vibration: ^3.1.3

  fluttertoast: ^8.2.12

dev_dependencies:

  build_runner: ^2.4.13

  retrofit_generator: ^9.1.5

  riverpod_generator: ^2.6.5

  freezed: ^3.0.4
