name: core_system
description: 'A core system for mmate'

publish_to: 'none'

version: 0.0.1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design
  function_system:
    path: ../function

  flutter_riverpod: ^2.6.1

  firebase_messaging: ^15.2.3
  firebase_core: ^3.12.0



