name: core_system
description: 'A core system for mmate'

publish_to: 'none'

version: 0.0.1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design
  function_system:
    path: ../function

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  firebase_messaging: ^15.2.3
  firebase_core: ^3.12.0

  flutter_localization: ^0.3.1

  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.0.0

  file_picker: ^9.0.0
  image_picker: ^1.1.2
  restart_app: ^1.3.2

  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15

  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

  freezed: ^3.0.4


